/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import Login.CommonDetails;
import Login.System_Login;
import Registration.Department_Registation;
import Registration.Sem_Year_Subject_Student;
import Registration.Semester_Year_Registration;
import Registration.Staff_Registration;
import Registration.Student_Registration;
import Registration.Subject_Registration;
import atendance.Class_Details;
import atendance.Mark_Claass_Details;
import atendance.Student_Attendane_Details;
import reporting.AttendanceReport;
import reporting.StudentReport;
import reporting.SubjectReport;

/**
 *
 * @author Dell
 */
public class MainApplication extends javax.swing.JFrame {

    /**
     * Creates new form MainApplication
     */
    public MainApplication() {
        initComponents();
        staff_name_lbl.setText(CommonDetails.userName + " !!!");
        provideAccess();
        CommonDetails.centerScreen(this);
    }

    public void provideAccess(){
    
        if (CommonDetails.isAdmin == false) {
        
           
            department_reg_btn.setEnabled(false);
            subject_reg_btn.setEnabled(false);
            student_reg_btn.setEnabled(false);
            staff_reg_btn.setEnabled(false);
            sem_year_reg_btn.setEnabled(false);
            sem_year_student_reg_btn.setEnabled(false);
            mark_class_btn.setEnabled(false);
            peentage_btn.setEnabled(false);
            mark_att_btn.setEnabled(false);
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staff_reg_btn = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        sem_year_reg_btn = new javax.swing.JToggleButton();
        sem_year_student_reg_btn = new javax.swing.JToggleButton();
        subject_reg_btn = new javax.swing.JToggleButton();
        department_reg_btn = new javax.swing.JToggleButton();
        student_reg_btn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        staff_name_lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mark_class_btn = new javax.swing.JButton();
        mark_att_btn = new javax.swing.JButton();
        peentage_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staff_reg_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        staff_reg_btn.setForeground(new java.awt.Color(0, 153, 0));
        staff_reg_btn.setText("Staff registraction");
        staff_reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_reg_btnActionPerformed(evt);
            }
        });
        getContentPane().add(staff_reg_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 410, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sem_year_reg_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sem_year_reg_btn.setForeground(new java.awt.Color(0, 153, 0));
        sem_year_reg_btn.setText("Semister Year And Subjects Registraction");
        sem_year_reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem_year_reg_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sem_year_reg_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 410, 40));

        sem_year_student_reg_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sem_year_student_reg_btn.setForeground(new java.awt.Color(0, 153, 0));
        sem_year_student_reg_btn.setText("Register Students For The Semisters");
        sem_year_student_reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem_year_student_reg_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sem_year_student_reg_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 410, 40));

        subject_reg_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subject_reg_btn.setForeground(new java.awt.Color(0, 153, 0));
        subject_reg_btn.setText("Subject Registrction");
        subject_reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject_reg_btnActionPerformed(evt);
            }
        });
        jPanel1.add(subject_reg_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 410, 40));

        department_reg_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        department_reg_btn.setForeground(new java.awt.Color(0, 153, 0));
        department_reg_btn.setText("Department Registraction");
        department_reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department_reg_btnActionPerformed(evt);
            }
        });
        jPanel1.add(department_reg_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 410, 40));

        student_reg_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        student_reg_btn.setForeground(new java.awt.Color(0, 153, 0));
        student_reg_btn.setText("Student Registaction");
        student_reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_reg_btnActionPerformed(evt);
            }
        });
        jPanel1.add(student_reg_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 450, 320));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Registraction");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        staff_name_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        staff_name_lbl.setForeground(new java.awt.Color(0, 51, 255));
        getContentPane().add(staff_name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 160, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        mark_class_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mark_class_btn.setForeground(new java.awt.Color(0, 51, 153));
        mark_class_btn.setText("Mark Class Details");
        mark_class_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark_class_btnActionPerformed(evt);
            }
        });

        mark_att_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mark_att_btn.setForeground(new java.awt.Color(0, 51, 153));
        mark_att_btn.setText("Mark Attendance Details");
        mark_att_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark_att_btnActionPerformed(evt);
            }
        });

        peentage_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        peentage_btn.setForeground(new java.awt.Color(0, 51, 153));
        peentage_btn.setText("Attendance percentage");
        peentage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peentage_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(peentage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mark_att_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mark_class_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mark_class_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mark_att_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(peentage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, 320));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 0, 102));
        jButton5.setText("Student Reports");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 0, 102));
        jButton6.setText("Student Attendance Reports");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 102));
        jButton4.setText("Subject Reports");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, 240));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Reporting");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, 41));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 630, 80, -1));

        jToggleButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton6.setForeground(new java.awt.Color(0, 153, 0));
        jToggleButton6.setText("Department Registraction");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 410, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Attendance Details");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Welcome ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 90, 20));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Log Out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void department_reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department_reg_btnActionPerformed
       this.dispose();
       new Department_Registation().setVisible(true);
       
        
    }//GEN-LAST:event_department_reg_btnActionPerformed

    private void student_reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_reg_btnActionPerformed
        this.dispose();
        new Student_Registration().setVisible(true);
    }//GEN-LAST:event_student_reg_btnActionPerformed

    private void sem_year_reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem_year_reg_btnActionPerformed
        this.dispose();
        new Semester_Year_Registration().setVisible(true);
    }//GEN-LAST:event_sem_year_reg_btnActionPerformed

    private void staff_reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_reg_btnActionPerformed
       this.dispose();
       new Staff_Registration().setVisible(true);
    }//GEN-LAST:event_staff_reg_btnActionPerformed

    private void subject_reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_reg_btnActionPerformed
       this.dispose();
       new Subject_Registration().setVisible(true);
    }//GEN-LAST:event_subject_reg_btnActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void mark_class_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark_class_btnActionPerformed
        this.dispose();
        new Mark_Claass_Details().setVisible(true);
    }//GEN-LAST:event_mark_class_btnActionPerformed

    private void mark_att_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark_att_btnActionPerformed
        this.dispose();
        new Class_Details().setVisible(true);
    }//GEN-LAST:event_mark_att_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sem_year_student_reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem_year_student_reg_btnActionPerformed
        this.dispose();
        new Sem_Year_Subject_Student().setVisible(true);
    }//GEN-LAST:event_sem_year_student_reg_btnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
        new System_Login().setVisible(true);
        CommonDetails.isAdmin = false;
        CommonDetails.staffId = "";
        CommonDetails.userName = "";
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        new StudentReport().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        new AttendanceReport().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new SubjectReport().setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void peentage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peentage_btnActionPerformed
        this.dispose();
        new Student_Attendane_Details().setVisible(true);
    }//GEN-LAST:event_peentage_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton department_reg_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JButton mark_att_btn;
    private javax.swing.JButton mark_class_btn;
    private javax.swing.JButton peentage_btn;
    private javax.swing.JToggleButton sem_year_reg_btn;
    private javax.swing.JToggleButton sem_year_student_reg_btn;
    private javax.swing.JLabel staff_name_lbl;
    private javax.swing.JToggleButton staff_reg_btn;
    private javax.swing.JToggleButton student_reg_btn;
    private javax.swing.JToggleButton subject_reg_btn;
    // End of variables declaration//GEN-END:variables
}
