/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reporting;

import DB_Connection.DB_Connection;
import Login.CommonDetails;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.MainApplication;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dthameera
 */
public class SubjectReport extends javax.swing.JFrame {

    /**
     * Creates new form StudentReport
     */
    public SubjectReport() {
        initComponents();
        CommonDetails.centerScreen(this);
        departmentSelection();
    }
    public void departmentSelection(){
    String sql= "select department_name from department";
    DB_Connection con = new DB_Connection();
    ResultSet r = con.search(sql);
        try {
            while(r.next()){
              department_combox.addItem(r.getString("department_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sem_yearLevel_text = new javax.swing.JTextField();
        semester_level_text = new javax.swing.JTextField();
        semester_combox = new javax.swing.JComboBox<>();
        semester_search_text = new javax.swing.JToggleButton();
        semester_year_combox = new javax.swing.JComboBox<>();
        academic_year_text = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        semester_year_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        department_text = new javax.swing.JTextField();
        department_combox = new javax.swing.JComboBox<>();
        sem_lable = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sem_yearLevel_text.setEditable(false);
        sem_yearLevel_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem_yearLevel_textActionPerformed(evt);
            }
        });
        getContentPane().add(sem_yearLevel_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 100, 30));

        semester_level_text.setEditable(false);
        semester_level_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester_level_textActionPerformed(evt);
            }
        });
        getContentPane().add(semester_level_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 140, 30));

        semester_combox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        semester_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester Level", "First Semester", "Second Semester" }));
        semester_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester_comboxActionPerformed(evt);
            }
        });
        getContentPane().add(semester_combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 140, 40));

        semester_search_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        semester_search_text.setText("Search");
        semester_search_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester_search_textActionPerformed(evt);
            }
        });
        getContentPane().add(semester_search_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 610, 40));

        semester_year_combox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        semester_year_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year Level", "First Year", "Second Year", "Third Year", "Fourth Year" }));
        semester_year_combox.setToolTipText("");
        semester_year_combox.setName("ss"); // NOI18N
        semester_year_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester_year_comboxActionPerformed(evt);
            }
        });
        getContentPane().add(semester_year_combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 100, 40));

        academic_year_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        academic_year_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academic_year_textActionPerformed(evt);
            }
        });
        getContentPane().add(academic_year_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 140, 30));

        semester_year_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sem Year Sub ID", "Subject Name", "Subject Code"
            }
        ));
        jScrollPane4.setViewportView(semester_year_table);
        if (semester_year_table.getColumnModel().getColumnCount() > 0) {
            semester_year_table.getColumnModel().getColumn(0).setMinWidth(0);
            semester_year_table.getColumnModel().getColumn(0).setPreferredWidth(0);
            semester_year_table.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 610, 310));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText(" Year");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 60, 40));

        department_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        department_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department_textActionPerformed(evt);
            }
        });
        getContentPane().add(department_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 230, 30));

        department_combox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        department_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select or Type  Department" }));
        department_combox.setToolTipText("");
        department_combox.setName("ss"); // NOI18N
        department_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department_comboxActionPerformed(evt);
            }
        });
        getContentPane().add(department_combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 230, 40));

        sem_lable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(sem_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 200, 30));

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 70, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 20, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 20, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 20, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 20, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("*");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 20, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Semester Year Subject Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 390, 51));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 30, 20));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Main Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 160, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("Main Menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 160, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 0, 0));
        jButton8.setText("Main Menu");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 160, 30));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("Exit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sem_yearLevel_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem_yearLevel_textActionPerformed

    }//GEN-LAST:event_sem_yearLevel_textActionPerformed

    private void semester_level_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester_level_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semester_level_textActionPerformed

    private void semester_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester_comboxActionPerformed
        String searchValue = semester_combox.getSelectedItem().toString();
        semester_level_text.setText(searchValue);
    }//GEN-LAST:event_semester_comboxActionPerformed

    private void semester_search_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester_search_textActionPerformed

        if (academic_year_text.getText().equals("") || semester_year_combox.getSelectedIndex() == 0 || 
                semester_combox.getSelectedIndex() == 0 || department_combox.getSelectedIndex() == 0 ) {
            JOptionPane.showMessageDialog(null, "Please Enter Accademic Year, year level, semester level, department", "information box"
                + "Warning", JOptionPane.INFORMATION_MESSAGE);
        } else {
           
            String sql= "select sem_year_sub_id, subject_name, subject_code, academic_year, year_level, semester_level, \n" +
            "    department_name from semester_year_subject inner join subject \n" +
            "    on semester_year_subject.subject_id =subject.subject_id inner join \n" +
            "    department on subject.department_id=department.department_id inner join \n" +
            "    semester_year on semester_year_subject.semester_year_id=semester_year.semester_year_id where "
            +   "semester_year.academic_year="+academic_year_text.getText()+" and semester_year.year_level= '"+sem_yearLevel_text.getText()+"'"
            + " and semester_year.semester_level= '"+semester_level_text.getText()+"' and "
            + "department.department_name= '"+department_text.getText()+"'";
            

            DB_Connection con = new DB_Connection();
            ResultSet g=con.search(sql);
            try{
                DefaultTableModel tableModel = (DefaultTableModel)semester_year_table.getModel();
                tableModel.setRowCount(0);
                String sem = academic_year_text.getText()+"-"+sem_yearLevel_text.getText()+"-"+semester_level_text.getText()+"-"+
                department_text.getText();
                sem_lable.setText(sem);
                while(g.next()){

                    Object[] arr = new Object[]{g.getString("sem_year_sub_id"),g.getString("subject_name"),
                        g.getString("subject_code"),g.getString("department_name")};
                    tableModel.addRow(arr);
                }
            }

            catch(Exception ex){

            }
        }
        
    }//GEN-LAST:event_semester_search_textActionPerformed

    private void semester_year_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester_year_comboxActionPerformed
        String searchValue = semester_year_combox.getSelectedItem().toString();
        sem_yearLevel_text.setText(searchValue);
    }//GEN-LAST:event_semester_year_comboxActionPerformed

    private void academic_year_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academic_year_textActionPerformed

    }//GEN-LAST:event_academic_year_textActionPerformed

    private void department_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_department_textActionPerformed

    private void department_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department_comboxActionPerformed
        String searchValue= department_combox.getSelectedItem().toString();
        department_text.setText(searchValue);
    }//GEN-LAST:event_department_comboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JRTableModelDataSource dt = new JRTableModelDataSource(semester_year_table.getModel());
            Map para = new HashMap();
            String sem = academic_year_text.getText() + " - " + semester_year_combox.getSelectedItem().toString() + " - " 
                    + semester_combox.getSelectedItem().toString();
            para.put("sem", sem);
            
            JasperReport jr = JasperCompileManager.compileReport("C:\\jasper\\Blank_A4.jrxml");
            JasperPrint jp = JasperFillManager.fillReport(jr, para, dt);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new MainApplication().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        new MainApplication().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
        new MainApplication().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField academic_year_text;
    private javax.swing.JComboBox<String> department_combox;
    private javax.swing.JTextField department_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel sem_lable;
    private javax.swing.JTextField sem_yearLevel_text;
    private javax.swing.JComboBox<String> semester_combox;
    private javax.swing.JTextField semester_level_text;
    private javax.swing.JToggleButton semester_search_text;
    private javax.swing.JComboBox<String> semester_year_combox;
    private javax.swing.JTable semester_year_table;
    // End of variables declaration//GEN-END:variables
}
