/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registration;

import DB_Connection.DB_Connection;
import Login.CommonDetails;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.MainApplication;

/**
 *
 * @author Dell
 */
public class Department_Registation extends javax.swing.JFrame {

    /**
     * Creates new form Department_Registation
     */
    public Department_Registation() {
        initComponents();
        CommonDetails.centerScreen(this);
        id_text.setVisible(false);
    }
    
    public void clearTextFields() {
    
        id_text.setText("");
        name_text.setText("");
    }
    public boolean isDepartmentExxist(String depName, String depId) { 
        try {
            String sql = "select * from department where department_name = '"+depName+"' and department_id != "+depId+"";
            DB_Connection con = new DB_Connection();
            ResultSet r = con.search(sql);
            if (r.next()) {
                
                return true;
            }
        } catch (Exception e) {
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        registration = new javax.swing.JToggleButton();
        id_text = new javax.swing.JTextField();
        name_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        department_table = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        staff_combo = new javax.swing.JComboBox<>();
        search_combo_text = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Department Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 140, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Department Registraction");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 340, 51));

        registration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registration.setText("Register Department");
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        getContentPane().add(registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 180, 43));

        id_text.setEditable(false);
        id_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id_text.setEnabled(false);
        id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textActionPerformed(evt);
            }
        });
        getContentPane().add(id_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, 40));

        name_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textActionPerformed(evt);
            }
        });
        getContentPane().add(name_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 260, 40));

        department_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department ID", "department Name"
            }
        ));
        department_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                department_tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(department_table);
        if (department_table.getColumnModel().getColumnCount() > 0) {
            department_table.getColumnModel().getColumn(0).setMinWidth(0);
            department_table.getColumnModel().getColumn(0).setPreferredWidth(0);
            department_table.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 510, 170));

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton1.setText("Search");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 180, 40));

        staff_combo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staff_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Department Name" }));
        staff_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_comboActionPerformed(evt);
            }
        });
        getContentPane().add(staff_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 170, 40));

        search_combo_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_combo_textActionPerformed(evt);
            }
        });
        getContentPane().add(search_combo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 160, 40));

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton2.setText("Update");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 180, 40));

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton3.setText("Edit");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 120, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 160, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 60, 30));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 640, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
        try{
            
            if (name_text.getText().equals("")) {
                 JOptionPane.showMessageDialog( null,"Please enter department name", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);

            }else if (isDepartmentExxist(name_text.getText(), "0")) {
                 JOptionPane.showMessageDialog( null,"This department is already exist", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);

            } else{
            String sql = "insert into department(department_name)values('"+name_text.getText()+"')";
            System.out.println(sql);
            DB_Connection con = new DB_Connection();

            int id =  con.register(sql);

            DefaultTableModel model = (DefaultTableModel)department_table.getModel();

            model.addRow(new Object[]{id, name_text.getText()});
            clearTextFields();
        }
        }
        catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_registrationActionPerformed

    private void id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_id_textActionPerformed

    private void name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            clearTextFields();
            DefaultTableModel model = (DefaultTableModel)department_table.getModel();
            model.setRowCount(0);
            model.setRowCount(0);
            String sql = "select * from department";
            if (!search_combo_text.getText().equals("")) {
                sql = sql + " where department_name like '"+search_combo_text.getText()+"%'";
            }
                DB_Connection con = new DB_Connection();
                ResultSet r = con.search(sql);
                search_combo_text.setText("");
                while (r.next()) {
            
                model.addRow(new Object[]{r.getString("department_id"), r.getString("department_name")});
       
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void staff_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_comboActionPerformed

    private void search_combo_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_combo_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_combo_textActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        try {
            int row = department_table.getSelectedRow();
            if (id_text.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please select Department", "information box" 
                        + "Warning", JOptionPane.INFORMATION_MESSAGE);
            } else if (isDepartmentExxist(name_text.getText(), id_text.getText())) {
            JOptionPane.showMessageDialog(null, "This department is already exist.", "information box" 
                        + "Warning", JOptionPane.INFORMATION_MESSAGE);
            } else {
            
                String sql = "update department set department_name = '"+name_text.getText()+"' where "
                        + " department_id = "+id_text.getText()+"";
                
                DB_Connection con = new DB_Connection();
                con.register(sql);
                department_table.setValueAt(name_text.getText(), row, 1);       
                department_table.clearSelection();
                clearTextFields();
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed

        try {
            int row = department_table.getSelectedRow();
            if(row==-1){
            JOptionPane.showMessageDialog( null,"Please select department table", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);
            }else{
                
                String depId = (department_table.getModel().getValueAt(row, 0).toString());
                String depName = (department_table.getModel().getValueAt(row, 1).toString());
                
                id_text.setText(depId);
                name_text.setText(depName);
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new MainApplication().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void department_tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_department_tableMousePressed
       clearTextFields();
    }//GEN-LAST:event_department_tableMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Department_Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Department_Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Department_Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Department_Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Department_Registation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable department_table;
    private javax.swing.JTextField id_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField name_text;
    private javax.swing.JToggleButton registration;
    private javax.swing.JTextField search_combo_text;
    private javax.swing.JComboBox<String> staff_combo;
    // End of variables declaration//GEN-END:variables
}
