/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registration;

import DB_Connection.DB_Connection;
import Login.CommonDetails;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.MainApplication;

/**
 *
 * @author Dell
 */
public class Semester_Year_Registration extends javax.swing.JFrame {

    /**
     * Creates new form Semester_Year_Registration
     */
    public Semester_Year_Registration() {
        initComponents();
        departmentDetails();
        CommonDetails.centerScreen(this);
        
    }
    public void departmentDetails(){
        String sql="select department_name from department";
         DB_Connection con = new DB_Connection();
         ResultSet r= con.search(sql);
        try {
            while(r.next()){
                department_combox.addItem(r.getString("department_name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Semester_Year_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
     
     public boolean isSubjectExistForTheSemester(){
           
            int row1 =semester_year_table.getSelectedRow();
            int row2 =subject_table.getSelectedRow();
            int semYearId = Integer.valueOf(semester_year_table.getModel().getValueAt(row1,0).toString());
            int subjectId = Integer.valueOf(subject_table.getModel().getValueAt(row2,0).toString());
         
         String sql="select * from semester_year_subject where semester_year_id = "+semYearId+" and subject_id = "+subjectId+" ";
         DB_Connection con = new DB_Connection();
         ResultSet r= con.search(sql);
        try {
            while(r.next()){
               return true;
            }
        } catch (SQLException ex) {
           
        }   
        return false;
    }
     
     public boolean isSemisterExist(){
           
            String academicYear = academic_year_text.getText();
            String yearLevel = semester_year_combox.getSelectedItem().toString();
            String  semesterLevel= semester_combox.getSelectedItem().toString();
         
         String sql="select * from semester_year where academic_year = "+academicYear+" and year_level = '"+yearLevel+"'"
                + " and semester_level = '"+semesterLevel+"' ";
         DB_Connection con = new DB_Connection();
         ResultSet r= con.search(sql);
        try {
            while(r.next()){
               return true;
            }
        } catch (SQLException ex) {
           
        }   
        return false;
    }
     
     public void clearTextFields() {
    
        academic_year_text.setText("");
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        subject_department_table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        semester_combox = new javax.swing.JComboBox<>();
        jToggleButton5 = new javax.swing.JToggleButton();
        semester_search_text = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        academic_year_text = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        semester_year_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        search_year_text = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        subject_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        semesterYearSubject_table = new javax.swing.JTable();
        jToggleButton6 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        credit_text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hours_text = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        department_combox = new javax.swing.JComboBox<>();
        subject_search_text = new javax.swing.JToggleButton();
        semester_year_combox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        acc_year_search_txt = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        subject_department_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester Year Subject ID", "Semester Year ID", "Subject ID", "Subject Name", "Department"
            }
        ));
        jScrollPane1.setViewportView(subject_department_table);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Adding Subjects into Related Academic Year/Year level/Semester Level & Department ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 970, 51));

        semester_combox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        semester_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester Level", "First Semester", "Second Semester" }));
        semester_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester_comboxActionPerformed(evt);
            }
        });
        getContentPane().add(semester_combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 150, 40));

        jToggleButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton5.setText("Save");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 70, 40));

        semester_search_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        semester_search_text.setText("Search");
        semester_search_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester_search_textActionPerformed(evt);
            }
        });
        getContentPane().add(semester_search_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 130, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setLabel("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 80, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 100, 20));

        academic_year_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        academic_year_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academic_year_textActionPerformed(evt);
            }
        });
        getContentPane().add(academic_year_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 30));

        semester_year_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester Year ID", "Academic Year", "Year Level", "Semester Level", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        semester_year_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semester_year_tableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                semester_year_tableMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                semester_year_tableMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(semester_year_table);
        if (semester_year_table.getColumnModel().getColumnCount() > 0) {
            semester_year_table.getColumnModel().getColumn(0).setMinWidth(0);
            semester_year_table.getColumnModel().getColumn(0).setPreferredWidth(0);
            semester_year_table.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 420, 170));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Enter the academic year");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Academic Year");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        search_year_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search_year_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_year_textActionPerformed(evt);
            }
        });
        getContentPane().add(search_year_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 130, 30));

        subject_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID", "Subject Name", "Subject Code", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(subject_table);
        if (subject_table.getColumnModel().getColumnCount() > 0) {
            subject_table.getColumnModel().getColumn(0).setMinWidth(0);
            subject_table.getColumnModel().getColumn(0).setPreferredWidth(0);
            subject_table.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 380, 170));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Add subject into related department with related semester year");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 470, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Acc Year");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 70, 30));

        semesterYearSubject_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester year Subject ID", "Academic Year", "Year Level", "Semester Level", "Subject Name", "Subject Code", "Credit", "Hours"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(semesterYearSubject_table);
        if (semesterYearSubject_table.getColumnModel().getColumnCount() > 0) {
            semesterYearSubject_table.getColumnModel().getColumn(0).setMinWidth(0);
            semesterYearSubject_table.getColumnModel().getColumn(0).setPreferredWidth(0);
            semesterYearSubject_table.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 810, 160));

        jToggleButton6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jToggleButton6.setText("Save Semester Year Subject Details");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Hours for a subject");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 140, 30));

        credit_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        credit_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credit_textActionPerformed(evt);
            }
        });
        getContentPane().add(credit_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 210, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Credits for a subject");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 180, 30));

        hours_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hours_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hours_textActionPerformed(evt);
            }
        });
        getContentPane().add(hours_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 210, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Main Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 160, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 600, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Semester Year Details");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 190, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        department_combox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        department_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department Name" }));
        department_combox.setToolTipText("");
        department_combox.setName("ss"); // NOI18N
        department_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department_comboxActionPerformed(evt);
            }
        });
        jPanel2.add(department_combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        subject_search_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subject_search_text.setText("Search");
        subject_search_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject_search_textActionPerformed(evt);
            }
        });
        jPanel2.add(subject_search_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 420, 290));

        semester_year_combox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        semester_year_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year Level", "First Year", "Second Year", "Third Year", "Fourth Year" }));
        semester_year_combox.setToolTipText("");
        semester_year_combox.setName("ss"); // NOI18N
        semester_year_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester_year_comboxActionPerformed(evt);
            }
        });
        getContentPane().add(semester_year_combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 150, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 630, 290));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Add Semister Years");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 30));
        getContentPane().add(acc_year_search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 80, 30));

        jButton5.setText("Search Subjects");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Enter the academic year");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 190, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Subject Details");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 190, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void semester_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester_comboxActionPerformed


    }//GEN-LAST:event_semester_comboxActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        try {
            if (academic_year_text.getText().equals("") || semester_year_combox.getSelectedIndex() == 0 || semester_combox.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog( null,"Please enter academic year and select semester year and semester level", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
            else if (isSemisterExist()) {
            JOptionPane.showMessageDialog( null,"This acadimic year, semister is already exist", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);

            }
            
            else{
                String semesterYear = semester_year_combox.getSelectedItem().toString();
                String semester= semester_combox.getSelectedItem().toString();
                
            String sql= "insert into semester_year(academic_year,year_level,semester_level)values"
                    + "('"+academic_year_text.getText()+"','"+semesterYear+"',"
                    + "'"+semester+"')";
            DB_Connection con =  new DB_Connection();
            int id=con.register(sql);
            DefaultTableModel model = (DefaultTableModel)semester_year_table.getModel();
            model.addRow(new Object[]{id,academic_year_text.getText(),semesterYear,semester});
              clearTextFields();  
            }}
        catch (Exception e) {

        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed
private void clearSelection() {
    
    credit_text.setText("");
    hours_text.setText("");
    DefaultTableModel model = (DefaultTableModel)semester_year_table.getModel();
    model.setRowCount(0);
    
    DefaultTableModel model2 = (DefaultTableModel)subject_table.getModel();
    model2.setRowCount(0);

}
    private void semester_year_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester_year_comboxActionPerformed
       
    }//GEN-LAST:event_semester_year_comboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*        try {
            String sql = "update student set student_id='"+id_text.getText()+"',first_name='"+fName_text.getText()+"',"
            + "last_name='"+lName_text.getText()+"',nic_num='"+nic_text.getText()+"',reg_num='"+reg_text.getText()+"',"
            + "age='"+age_text.getText()+"',address='"+address_text.getText()+"',tp_num='"+tp_text.getText()+"' where student_id='"+id_text.getText()+"'";
            System.out.println(sql);
            DB_Connection con=new DB_Connection();
            con.register(sql);

            int row = student_table.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel)student_table.getModel();
            model.setValueAt(id_text.getText(),row,0);
            model.setValueAt(fName_text.getText(), row, 1);
            model.setValueAt(lName_text.getText(), row, 2);
            model.setValueAt(nic_text.getText(), row, 3);
            model.setValueAt(reg_text.getText(), row, 4);
            model.setValueAt(age_text.getText(), row, 5);
            model.setValueAt(address_text.getText(),row,6);
            model.setValueAt(tp_text.getText(), row, 7);

        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*        try {
            int row = student_table.getSelectedRow();

            String studentId =  student_table.getModel().getValueAt(row, 0).toString();
            String firstName =  student_table.getModel().getValueAt(row, 1).toString();
            String lastName =  student_table.getModel().getValueAt(row, 2).toString();
            String nicNumber = student_table.getModel().getValueAt(row,3).toString();
            String regNo =  student_table.getModel().getValueAt(row,4).toString();
            String age =  student_table.getModel().getValueAt(row, 5).toString();
            String address=student_table.getModel().getValueAt(row,6).toString();
            String telephoneNum=student_table.getModel().getValueAt(row,7).toString();

            id_text.setText(studentId);
            fName_text.setText(firstName);
            lName_text.setText(studentId);
            nic_text.setText(nicNumber);
            reg_text.setText(regNo);
            age_text.setText(age);
            address_text.setText(address);
            tp_text.setText(telephoneNum);

        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void academic_year_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academic_year_textActionPerformed

    }//GEN-LAST:event_academic_year_textActionPerformed

    private void search_year_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_year_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_year_textActionPerformed

    private void department_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department_comboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_department_comboxActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
      try {
            int yearTable = semester_year_table.getSelectedRow();
            int subTable = subject_table.getSelectedRow();
            if (yearTable == -1 || subTable == -1 || credit_text.getText().equals("") || credit_text.getText().equals("0") || 
                    hours_text.getText().equals("") || hours_text.getText().equals("0")) {
            
            JOptionPane.showMessageDialog( null,"Please select sem year, subject, credit and hours", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);

            } else {
            int semYearRowCount = semester_year_table.getRowCount();
            String credit =credit_text.getText().equals("") ? "0": credit_text.getText();
            String hours = hours_text.getText().equals("") ? "0": hours_text.getText();
            DB_Connection con =  new DB_Connection();
            DefaultTableModel model = (DefaultTableModel)semesterYearSubject_table.getModel();
            model.setRowCount(0);
            for (int i =0; i< semYearRowCount; i++) {
            
                boolean isSelect = semester_year_table.getModel().getValueAt(i,4) == null ? false : 
                        Boolean.valueOf(semester_year_table.getModel().getValueAt(i,4).toString());               
                if (true == isSelect) {
                    int semYearId = Integer.valueOf(semester_year_table.getModel().getValueAt(i,0).toString());
                    String academicYear = semester_year_table.getModel().getValueAt(i, 1).toString();
                    String yearLevel = semester_year_table.getModel().getValueAt(i, 2).toString();
                    String  semesterLevel= semester_year_table.getModel().getValueAt(i, 3).toString();
                    
                    int subjectRowCount = subject_table.getRowCount();
            
                    for (int y = 0; y<subjectRowCount; y++) {
                            boolean isSubSelect = subject_table.getModel().getValueAt(y,3) == null ? false : 
                            Boolean.valueOf(subject_table.getModel().getValueAt(y,3).toString());  
                            int id=0;
                    if (isSubSelect ) {
                        int subjectId = Integer.valueOf(subject_table.getModel().getValueAt(y,0).toString());
                        String  subjectName= subject_table.getModel().getValueAt(y,1).toString();
                        String  subjectCode= subject_table.getModel().getValueAt(y,2).toString();
                        
                        String search= "select sys.sem_year_sub_id from semester_year_subject sys inner join "
                                + "semester_year sy on sys.semester_year_id =sy.semester_year_id where "
                                + "sys.subject_id ="+subjectId+" and sy.academic_year ="+academicYear+"";
                        ResultSet r=  con.search(search);
                        if (r.next()) {                            
                          JOptionPane.showMessageDialog( null,subjectName + "is already exist", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);                  
                         } else {
                           String sql= "insert into semester_year_subject(semester_year_id,subject_id,credit,hours)values("+semYearId+","+subjectId+","+credit+","+hours+")";
                        
                         id=con.register(sql);
                         model.addRow(new Object[]{id,academicYear,yearLevel,semesterLevel,subjectName,subjectCode, credit, hours});
                        }
                                            }
                    } 
                } 
                
            }
            clearSelection();
            }
            
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void credit_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credit_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credit_textActionPerformed

    private void hours_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hours_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hours_textActionPerformed

    private void subject_search_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_search_textActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel)subject_table.getModel();
        tableModel.setRowCount(0);
        String searchValue = department_combox.getSelectedItem().toString();
      
        String sql="select subject_id,subject_name,subject_code from subject inner join department on subject.department_id=department.department_id where department_name='"+searchValue+"' ";
        DB_Connection con = new DB_Connection();
        ResultSet r=  con.search(sql);
        try {
            if(searchValue=="Select Department Name"){
            JOptionPane.showMessageDialog( null,"Please select department", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);
            
            }
            else{
            
            while(r.next()){
                Object[] arr = new Object[]{r.getString("subject_id"),r.getString("subject_name"),
                    r.getString("subject_code")};
                tableModel.addRow(arr);
            }
        }
        }
        catch(Exception ex){
        }

    }//GEN-LAST:event_subject_search_textActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new MainApplication().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void semester_search_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester_search_textActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel)semester_year_table.getModel();
        tableModel.setRowCount(0);
        String sql="select * from semester_year where academic_year='"+search_year_text.getText()+"'";
        DB_Connection con = new DB_Connection();
        ResultSet g=con.search(sql);
        try{
            
            while(g.next()){
                Object[] arr = new Object[]{g.getString("semester_year_id"),g.getString("academic_year"),
                    g.getString("year_level"),g.getString("semester_level")};
                tableModel.addRow(arr);
            }    
        }

        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_semester_search_textActionPerformed

    private void semester_year_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semester_year_tableMouseClicked
        int rawCount = semester_year_table.getRowCount();
        int selectedRaw = semester_year_table.getSelectedRow();
        for (int i=0; i<rawCount; i++) {            
            if (i != selectedRaw) {
                semester_year_table.setValueAt(false, i, 4);
            }
            
        }
    }//GEN-LAST:event_semester_year_tableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
           
             DefaultTableModel model = (DefaultTableModel)semesterYearSubject_table.getModel();
             model.setRowCount(0);
        
        if (!acc_year_search_txt.getText().equals("")) {
        String sql = "select sys.sem_year_sub_id, sy.academic_year, sy.year_level, sy.semester_level, s.subject_name, s.subject_code, "
                + "sys.credit, sys.hours from semester_year_subject sys "
                + "inner join semester_year sy on sys.semester_year_id =sy.semester_year_id  "
                + "inner join subject s on s.subject_id = sys.subject_id where sy.academic_year ="+acc_year_search_txt.getText()+"";
         DB_Connection con = new DB_Connection();
        ResultSet r = con.search(sql);
        while (r.next()) {
          model.addRow(new Object[]{r.getInt("sem_year_sub_id"), r.getInt("academic_year"),r.getString("year_level"),r.getString("semester_level"),
              r.getString("subject_name"),r.getString("subject_code"), 
              r.getInt("credit"), r.getInt("hours")});
 
        }
        } else {
        JOptionPane.showMessageDialog( null,"Please enter Acc Year", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);

        }
        acc_year_search_txt.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void semester_year_tableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semester_year_tableMouseEntered
       int rawCount = semester_year_table.getRowCount();
        int selectedRaw = semester_year_table.getSelectedRow();
        for (int i=0; i<rawCount; i++) {            
            if (i != selectedRaw) {
                semester_year_table.setValueAt(false, i, 4);
            }
            
        }
    }//GEN-LAST:event_semester_year_tableMouseEntered

    private void semester_year_tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semester_year_tableMousePressed
       int rawCount = semester_year_table.getRowCount();
        int selectedRaw = semester_year_table.getSelectedRow();
        for (int i=0; i<rawCount; i++) {            
            if (i != selectedRaw) {
                semester_year_table.setValueAt(false, i, 4);
            }
            
        }
    }//GEN-LAST:event_semester_year_tableMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Semester_Year_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Semester_Year_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Semester_Year_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Semester_Year_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Semester_Year_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField academic_year_text;
    private javax.swing.JTextField acc_year_search_txt;
    private javax.swing.JTextField credit_text;
    private javax.swing.JComboBox<String> department_combox;
    private javax.swing.JTextField hours_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JTextField search_year_text;
    private javax.swing.JTable semesterYearSubject_table;
    private javax.swing.JComboBox<String> semester_combox;
    private javax.swing.JToggleButton semester_search_text;
    private javax.swing.JComboBox<String> semester_year_combox;
    private javax.swing.JTable semester_year_table;
    private javax.swing.JTable subject_department_table;
    private javax.swing.JToggleButton subject_search_text;
    private javax.swing.JTable subject_table;
    // End of variables declaration//GEN-END:variables
}
