/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registration;

import DB_Connection.DB_Connection;
import Login.CommonDetails;
import Login.System_Login;
import java.sql.ResultSet;
import java.sql.Types;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.MainApplication;

/**
 *
 * @author Dell
 */
public class Staff_Registration extends javax.swing.JFrame {

    /**
     * Creates new form Staff
     */
    public Staff_Registration() {
        initComponents();
        id_text.setVisible(false);
        provideAccess();
        CommonDetails.centerScreen(this);
    }
    
    public void provideAccess() {
    
        if(!CommonDetails.isAdmin) {
        
            search_combo.setVisible(false);
            search_btn.setVisible(false);
            search_text.setVisible(false);
            update_btn.setVisible(false);
            edit_btn.setVisible(false);
            is_admin_chk.setVisible(false);
            is_admin_lbl.setVisible(false);
            edit_btn1.setVisible(false);
        }
        
        if (CommonDetails.staffId.equals("")) {
            main_btn.setVisible(false);
        } else {
            login_btn.setVisible(false);
        }
    }
    
     public boolean isNicExist(String nic, String id) {      
        try {
        String sql = "select * from staff where nic_num = '"+nic+"' and staff_id !="+id+"";
    
        DB_Connection con = new DB_Connection();
        ResultSet r = con.search(sql);
        if (r.next()) {
        return true;
        } 
        } catch (Exception e) {
        }
        return false;
    }
    
    public boolean isValidStaffDetails(String id) {
    
        if (user_name_txt.getText().equals("") || password_text.getText().equals("")) {
      JOptionPane.showMessageDialog( null,"Provide user name and password", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
      return false;
      
   } 
        else if (isPasswordExist(user_name_txt.getText(), password_text.getText(), id)){
   JOptionPane.showMessageDialog( null,"This user name or pasword already exist", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
   return false;
   }else if (!CommonDetails.isValidPassword(password_text.getText())) {
       JOptionPane.showMessageDialog( null,"Please enter valid password", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
       return false;
   } else if (CommonDetails.isValidEmail(email_text.getText()) == false) {
    JOptionPane.showMessageDialog( null,"Provide valid email address", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
    return false;
   } else if (fName_text.getText().equals("") || lName_text.getText().equals("") || nic_text.getText().equals("") || 
           email_text.getText().equals("")) {
    JOptionPane.showMessageDialog( null,"Please enter all mandatory fields", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
    return false;
   }
    else if (isNicExist(nic_text.getText(),id)) {
    JOptionPane.showMessageDialog( null,"NIC number is already exist.", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
    return false;
   }  
        return true;
   }
    public void clearStaffTable() {
    
        DefaultTableModel table = (DefaultTableModel)staff_table.getModel();
        table.setRowCount(0);
    }
    
    public boolean isPasswordExist(String userName, String password, String id) {
        
        try {
        String sql = "select * from staff where (user_name ="
                           + " '"+userName+"' or password = '"+password+"') and is_delete = false and staff_id !=  "+id+"";
    
        DB_Connection con = new DB_Connection();
        ResultSet r = con.search(sql);
        if (r.next()) {
        return true;
        } else {
        return false;
        }
        } catch (Exception e) {
        }
        return false;
    }
    public void clearTextFields() {
    
        lName_text.setText("");
        fName_text.setText("");
        email_text.setText("");
        nic_text.setText("");
        tp_text.setText("");
        address_text.setText("");
        age_text.setText("");
        id_text.setText("");
        user_name_txt.setText("");
        password_text.setText("");
        is_teacher_combo.setSelected(false);
        is_admin_chk.setSelected(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        registration = new javax.swing.JToggleButton();
        id_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        staff_table = new javax.swing.JTable();
        search_btn = new javax.swing.JToggleButton();
        search_combo = new javax.swing.JComboBox<>();
        search_text = new javax.swing.JTextField();
        update_btn = new javax.swing.JToggleButton();
        edit_btn = new javax.swing.JToggleButton();
        main_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lName_text = new javax.swing.JTextField();
        age_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tp_text = new javax.swing.JTextField();
        is_teacher_combo = new javax.swing.JCheckBox();
        is_admin_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nic_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        address_text = new javax.swing.JTextField();
        email_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fName_text = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        user_name_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        password_text = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        is_admin_chk = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        edit_btn1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Staff Registation");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 51));

        registration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registration.setText("Register Staff");
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        getContentPane().add(registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 155, 43));

        id_text.setEditable(false);
        id_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id_text.setEnabled(false);
        id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textActionPerformed(evt);
            }
        });
        getContentPane().add(id_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 90, 32));

        staff_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "First Name", "Last Name", "NIC Num:", "Age", "Address", "Telephone Num", "Email", "Is Lecturer", "User Name", "Password", "Is Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        staff_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staff_tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(staff_table);
        if (staff_table.getColumnModel().getColumnCount() > 0) {
            staff_table.getColumnModel().getColumn(0).setMinWidth(0);
            staff_table.getColumnModel().getColumn(0).setPreferredWidth(0);
            staff_table.getColumnModel().getColumn(0).setMaxWidth(0);
            staff_table.getColumnModel().getColumn(3).setResizable(false);
            staff_table.getColumnModel().getColumn(9).setMinWidth(0);
            staff_table.getColumnModel().getColumn(9).setPreferredWidth(0);
            staff_table.getColumnModel().getColumn(9).setMaxWidth(0);
            staff_table.getColumnModel().getColumn(10).setMinWidth(0);
            staff_table.getColumnModel().getColumn(10).setPreferredWidth(0);
            staff_table.getColumnModel().getColumn(10).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 810, 160));

        search_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 160, 40));

        search_combo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff ID", "First Name", "Last Name", "NIC Num", "Email", "Is Lecturer" }));
        search_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_comboActionPerformed(evt);
            }
        });
        getContentPane().add(search_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 40));

        search_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_textActionPerformed(evt);
            }
        });
        getContentPane().add(search_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 170, 40));

        update_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 130, 40));

        edit_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit_btn.setText("Edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(edit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 110, -1));

        main_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        main_btn.setForeground(new java.awt.Color(255, 0, 0));
        main_btn.setText("Main Menu");
        main_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_btnActionPerformed(evt);
            }
        });
        getContentPane().add(main_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 660, 160, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 660, -1, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 122, 30));

        lName_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lName_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lName_textKeyTyped(evt);
            }
        });
        jPanel1.add(lName_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 170, 30));

        age_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        age_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                age_textKeyTyped(evt);
            }
        });
        jPanel1.add(age_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 170, 32));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Telephone Num:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        tp_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tp_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_textActionPerformed(evt);
            }
        });
        tp_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tp_textKeyTyped(evt);
            }
        });
        jPanel1.add(tp_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 162, 30));

        is_teacher_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                is_teacher_comboActionPerformed(evt);
            }
        });
        jPanel1.add(is_teacher_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 40, 30));

        is_admin_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        is_admin_lbl.setText("Is Admin");
        jPanel1.add(is_admin_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NIC Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 103, 24));

        nic_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nic_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nic_textKeyTyped(evt);
            }
        });
        jPanel1.add(nic_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 170, 33));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 79, 24));

        address_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(address_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 170, 30));

        email_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textActionPerformed(evt);
            }
        });
        jPanel1.add(email_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 30));

        fName_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fName_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fName_textActionPerformed(evt);
            }
        });
        fName_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fName_textKeyTyped(evt);
            }
        });
        jPanel1.add(fName_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 160, 31));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 20, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, 30));

        user_name_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user_name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                user_name_txtKeyTyped(evt);
            }
        });
        jPanel1.add(user_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 160, 32));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Is Lecturer");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Age");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 58, -1));

        password_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textActionPerformed(evt);
            }
        });
        jPanel1.add(password_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 170, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Password");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 90, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 20, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("(minimum characters is 8)");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 190, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("User Name");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, -1));

        is_admin_chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                is_admin_chkActionPerformed(evt);
            }
        });
        jPanel1.add(is_admin_chk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 103, 29));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("ex - Example@user20");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 770, 310));

        login_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_btn.setForeground(new java.awt.Color(255, 0, 0));
        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, 160, 30));

        edit_btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit_btn1.setText("Remove Selected Staff");
        edit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(edit_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
try{

   if (isValidStaffDetails("0")) {
      int tel = tp_text.getText().equals("") ? 0 : Integer.valueOf(tp_text.getText());
           int age = age_text.getText().equals("") ? 0 : Integer.valueOf(age_text.getText());
           boolean isTeacher = is_teacher_combo.isSelected();
            String sql = "insert into staff(first_name,last_name,nic_num,age,address,telephone_num,email,is_lecturer, user_name, password, is_admin, is_delete)values"
                    + "('"+fName_text.getText()+"','"+lName_text.getText()+"','"+nic_text.getText()+"',"+age+","
                    + "'"+address_text.getText()+"',"+tel+",'"+email_text.getText()+"','"+isTeacher+"', "
                    + "'"+user_name_txt.getText()+"', '"+password_text.getText()+"',"+is_admin_chk.isSelected()+", false)";
             DB_Connection con = new DB_Connection();
             System.out.println(sql);
              int id =  con.register(sql);
       
             DefaultTableModel model = (DefaultTableModel)staff_table.getModel();
         

           model.addRow(new Object[]{id, fName_text.getText(),lName_text.getText(),nic_text.getText(),
               age_text.getText(),address_text.getText(),tp_text.getText(),email_text.getText(),isTeacher});
           clearTextFields();
}      }    
        catch (Exception ex) {
            System.out.println(ex);
        }        
    }//GEN-LAST:event_registrationActionPerformed

    private void id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_id_textActionPerformed

    private void fName_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fName_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fName_textActionPerformed

    private void tp_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tp_textActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        clearStaffTable();
        clearTextFields();
        String sql="select * from staff where is_delete = false and ";
        DB_Connection con = new DB_Connection();
        String searchValue = search_combo.getSelectedItem().toString();

        if (searchValue.equals("Staff ID")) {
            sql = sql + "staff_id = '"+search_text.getText()+"'";
        }

        if (searchValue.equals("First Name")) {
            sql = sql + "first_name = '"+search_text.getText()+"'";
        }

        if (searchValue.equals("Last Name")){
            sql=sql+"last_name = '"+search_text.getText()+"'";
        }

        if (searchValue.equals("NIC Num")){
            sql=sql+"nic_num ='"+search_text.getText()+"'";}
                    
        if (searchValue.equals("Email")){
            sql=sql+"email_num ='"+search_text.getText()+"'";
        }
         if (searchValue.equals("Is Lecturer")){
            sql=sql+"is_lecturer ="+search_text.getText()+"";
        }

        ResultSet g=con.search(sql);
        search_text.setText("");

        try {
            DefaultTableModel tableModel = (DefaultTableModel)staff_table.getModel();
            while(g.next()){
                
                Object[] arr = new Object[]{g.getString("staff_id"),g.getString("first_name"),
                    g.getString("last_name"),g.getString("nic_num"),g.getString("age"),g.getString("address"),
                    g.getString("telephone_num"),g.getString("email"),g.getBoolean("is_lecturer"), 
                    g.getString("user_name"), g.getString("password"), g.getBoolean("is_admin")};
                tableModel.addRow(arr);
            }
        }
        catch(Exception ex){
        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void search_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_comboActionPerformed

    private void is_teacher_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_is_teacher_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_is_teacher_comboActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        try {
           int row = staff_table.getSelectedRow();
           
            if(row==-1){
            JOptionPane.showMessageDialog( null,"Please select one from student details table", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
           String staffId =  staff_table.getModel().getValueAt(row, 0).toString();
           String firstName = staff_table.getModel().getValueAt(row,1).toString();
           String lastName=staff_table.getModel().getValueAt(row,2).toString();
           String nicNum= staff_table.getModel().getValueAt(row,3).toString();
           String age = staff_table.getModel().getValueAt(row,4).toString();
           String address= staff_table.getModel().getValueAt(row,5).toString();
           String phone= staff_table.getModel().getValueAt(row,6).toString();
           String email= staff_table.getModel().getValueAt(row,7).toString();
           String isLecturer = staff_table.getModel().getValueAt(row,8).toString();
           String userName = staff_table.getModel().getValueAt(row,9).toString();
           String password = staff_table.getModel().getValueAt(row,10).toString();
           String isAdmin = staff_table.getModel().getValueAt(row,11).toString();
           boolean admin=Boolean.parseBoolean(isAdmin); 
           boolean lecture=Boolean.parseBoolean(isLecturer); 
                
           is_teacher_combo.setSelected(lecture);
           id_text.setText(staffId);
           fName_text.setText(firstName);
           lName_text.setText(lastName);
           nic_text.setText(nicNum);
           age_text.setText(age);
           address_text.setText(address);
           tp_text.setText(phone);
           email_text.setText(email);
           user_name_txt.setText(userName);
           password_text.setText(password);
           is_admin_chk.setSelected(admin);
            }
           
        } catch (Exception e) {
        }
    }//GEN-LAST:event_edit_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        try {
            
       String id = id_text.getText();
      if (isValidStaffDetails(id)) {    
       
       int tel = tp_text.getText().equals("") ? 0 : Integer.valueOf(tp_text.getText());
       int age = age_text.getText().equals("") ? 0 : Integer.valueOf(age_text.getText());
     String sql = "update staff set first_name='"+fName_text.getText()+"',last_name='"+lName_text.getText()+"',"
             + "nic_num='"+nic_text.getText()+"',age='"+age+"',address='"+address_text.getText()+"',"
             + "telephone_num='"+tel+"',email='"+email_text.getText()+"', "
             + "is_lecturer = "+is_teacher_combo.isSelected()+" , user_name = '"+user_name_txt.getText()+"' "
             + " , password = '"+password_text.getText()+"' , is_admin = "+is_admin_chk.isSelected()+" where staff_id='"+id_text.getText()+"'";
         int row = staff_table.getSelectedRow();
            DB_Connection con=new DB_Connection();
            con.register(sql);
            
             boolean isTeacher = is_teacher_combo.isSelected();
            DefaultTableModel model = (DefaultTableModel)staff_table.getModel();
            model.setValueAt(id_text.getText(),row,0);
            model.setValueAt(fName_text.getText(), row, 1);
            model.setValueAt(lName_text.getText(), row, 2);
            model.setValueAt(nic_text.getText(), row, 3);
            model.setValueAt(age, row, 4);
            model.setValueAt(address_text.getText(),row,5);
            model.setValueAt(tel, row, 6);
            model.setValueAt(email_text.getText(), row, 7);
            model.setValueAt(isTeacher, row, 8);
            model.setValueAt(user_name_txt.getText(), row, 9);
            model.setValueAt(password_text.getText(), row, 10);
            model.setValueAt(is_admin_chk.isSelected(), row, 11);

            clearTextFields();
   }
        } catch (Exception e) {
        }
                                     
    }//GEN-LAST:event_update_btnActionPerformed

    private void main_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_btnActionPerformed
        this.dispose();
        new MainApplication().setVisible(true);
    }//GEN-LAST:event_main_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void age_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_textKeyTyped
       char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_age_textKeyTyped

    private void lName_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lName_textKeyTyped
       char enter = evt.getKeyChar();
        if((Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_lName_textKeyTyped

    private void fName_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fName_textKeyTyped
       char enter = evt.getKeyChar();
        if((Character.isDigit(enter))){
            evt.consume();
        }
       
 
    }//GEN-LAST:event_fName_textKeyTyped

    private void tp_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tp_textKeyTyped
       char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
      if (tp_text.getText().length()>9) {
         evt.consume();
      }
    }//GEN-LAST:event_tp_textKeyTyped

    private void user_name_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_name_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_user_name_txtKeyTyped

    private void is_admin_chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_is_admin_chkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_is_admin_chkActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        this.dispose();
        new System_Login().setVisible(true);
    }//GEN-LAST:event_login_btnActionPerformed

    private void edit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btn1ActionPerformed
        try {
          int selectRows = staff_table.getSelectedRowCount();
          
          if (selectRows == 0) {
            JOptionPane.showMessageDialog( null,"Please select staff", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
          }else if (selectRows>1) {
            JOptionPane.showMessageDialog( null,"Please select only one staff", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
          } else {
          
              int row = staff_table.getSelectedRow();
              String sql = "update staff set is_delete = true where staff_id = "+staff_table.getValueAt(row, 0)+"";
              DB_Connection con = new DB_Connection();
              con.register(sql);
              
              DefaultTableModel model = (DefaultTableModel)staff_table.getModel();
              model.removeRow(row);
          }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_edit_btn1ActionPerformed

    private void staff_tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_tableMousePressed
        clearTextFields();
    }//GEN-LAST:event_staff_tableMousePressed

    private void nic_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic_textKeyTyped
       char enter = evt.getKeyChar();

       if(nic_text.getText().length()<=8){
            if(!(Character.isDigit(enter))){
            evt.consume();
        }
       }
          
        if (nic_text.getText().length()==9) {
           if((Character.isDigit(enter))){
            evt.consume();
        }
      }
        
        
         if (nic_text.getText().length()>9) {
           
            evt.consume();
        
      }
    }//GEN-LAST:event_nic_textKeyTyped

    private void email_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_textActionPerformed

    private void password_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_textActionPerformed

    private void search_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_text;
    private javax.swing.JTextField age_text;
    private javax.swing.JToggleButton edit_btn;
    private javax.swing.JToggleButton edit_btn1;
    private javax.swing.JTextField email_text;
    private javax.swing.JTextField fName_text;
    private javax.swing.JTextField id_text;
    private javax.swing.JCheckBox is_admin_chk;
    private javax.swing.JLabel is_admin_lbl;
    private javax.swing.JCheckBox is_teacher_combo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lName_text;
    private javax.swing.JButton login_btn;
    private javax.swing.JButton main_btn;
    private javax.swing.JTextField nic_text;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JToggleButton registration;
    private javax.swing.JToggleButton search_btn;
    private javax.swing.JComboBox<String> search_combo;
    private javax.swing.JTextField search_text;
    private javax.swing.JTable staff_table;
    private javax.swing.JTextField tp_text;
    private javax.swing.JToggleButton update_btn;
    private javax.swing.JTextField user_name_txt;
    // End of variables declaration//GEN-END:variables
}
