/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registration;

import DB_Connection.DB_Connection;
import Login.CommonDetails;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import main.MainApplication;

/**
 *
 * @author Dell
 */
public class Student_Registration extends javax.swing.JFrame {

    /**
     * Creates new form Student_Registration
     */
    public Student_Registration() {
        initComponents();
        department();
        id_text.setVisible(false);
        CommonDetails.centerScreen(this);
    }
    public boolean isNicExist(String nic, String id) {      
        try {
        String sql = "select * from student where nic_num = '"+nic+"' and student_id !="+id+"";
    
        DB_Connection con = new DB_Connection();
        ResultSet r = con.search(sql);
        if (r.next()) {
        return true;
        } 
        } catch (Exception e) {
        }
        return false;
    }
    public void clearTestFields() {
    
        fName_text.setText("");
        lName_text.setText("");
        nic_text.setText("");
        age_text.setText("");
        reg_text.setText("");
        address_text.setText("");
        tp_text.setText("");
        academicYear_Text.setText("");
        id_text.setText("");
                
    
    }
    public boolean isRegNoExist(String regNo, String id) {   
        try {
        String sql = "select * from student where reg_num = '"+regNo+"' and student_id !="+id+"";
    
        DB_Connection con = new DB_Connection();
        ResultSet r = con.search(sql);
        if (r.next()) {
        return true;
        } 
        } catch (Exception e) {
        }
        return false;
    }
    public boolean isValidStudentDetails(String id) {
    
        if (fName_text.getText().equals("") || lName_text.getText().equals("") || nic_text.getText().equals("") || 
             reg_text.getText().equals("") || academicYear_Text.getText().equals("")   ) {
            JOptionPane.showMessageDialog( null,"Please enter all mandatory fields", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
      return false;
   } 
       else if (isRegNoExist(reg_text.getText(), id)) {
       JOptionPane.showMessageDialog( null,"Registration number is already exist.", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
       return false;
   } else if (isNicExist(nic_text.getText(),id)) {
    JOptionPane.showMessageDialog( null,"NIC number is already exist.", "information box" + "Warning", 
            JOptionPane.INFORMATION_MESSAGE);
    return false;
   }  
        return true;
   }
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) student_table.getModel();
        model.setRowCount(0);
    }
    
    public void department(){
      String sql="select department_id,department_name from department";
         DB_Connection con = new DB_Connection();
         ResultSet r= con.search(sql);
       try{ 
           
             DefaultTableModel model= (DefaultTableModel) department_table.getModel();
             while(r.next()){
              model.addRow(new Object[]{r.getString("department_id"),r.getString("department_name")});
               
            }
         }

        catch(Exception ex){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registration = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        student_table = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        search_text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fName_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lName_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nic_text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        age_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        reg_text = new javax.swing.JTextField();
        academicYear_Text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tp_text = new javax.swing.JTextField();
        address_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        department_table = new javax.swing.JTable();
        id_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registration.setText("Register Student");
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        getContentPane().add(registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 155, 43));

        student_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First Name", "Last Name", "NIC Num:", "Reg Num:", "Age", "Address", "TP Num:", "Academic Year", "Department ID", "Department Name"
            }
        ));
        jScrollPane1.setViewportView(student_table);
        if (student_table.getColumnModel().getColumnCount() > 0) {
            student_table.getColumnModel().getColumn(0).setMinWidth(0);
            student_table.getColumnModel().getColumn(0).setPreferredWidth(0);
            student_table.getColumnModel().getColumn(0).setMaxWidth(0);
            student_table.getColumnModel().getColumn(9).setMinWidth(0);
            student_table.getColumnModel().getColumn(9).setPreferredWidth(0);
            student_table.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 1120, 160));

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton1.setText("Search");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 160, 40));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Id", "First Name", "Last name", "NIC Num", "Reg Num", "Academic Year" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 160, 40));

        search_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_textActionPerformed(evt);
            }
        });
        getContentPane().add(search_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 170, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 110, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Update Student Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 180, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("Student Registraction");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 280, 51));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Main Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, 160, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, -1, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 103, 30));

        fName_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fName_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fName_textActionPerformed(evt);
            }
        });
        fName_text.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fName_textPropertyChange(evt);
            }
        });
        fName_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fName_textKeyTyped(evt);
            }
        });
        jPanel1.add(fName_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 160, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 122, 30));

        lName_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lName_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lName_textActionPerformed(evt);
            }
        });
        lName_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lName_textKeyTyped(evt);
            }
        });
        jPanel1.add(lName_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NIC Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 103, 24));

        nic_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nic_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nic_textActionPerformed(evt);
            }
        });
        nic_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nic_textKeyTyped(evt);
            }
        });
        jPanel1.add(nic_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 160, 33));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Age");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 58, -1));

        age_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        age_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_textActionPerformed(evt);
            }
        });
        age_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                age_textKeyTyped(evt);
            }
        });
        jPanel1.add(age_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 170, 32));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Registration Num:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        reg_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reg_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_textActionPerformed(evt);
            }
        });
        jPanel1.add(reg_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, 30));

        academicYear_Text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        academicYear_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academicYear_TextActionPerformed(evt);
            }
        });
        academicYear_Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                academicYear_TextKeyTyped(evt);
            }
        });
        jPanel1.add(academicYear_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Academic  Year");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 120, 24));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Telephone Num:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        tp_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tp_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_textActionPerformed(evt);
            }
        });
        tp_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tp_textKeyTyped(evt);
            }
        });
        jPanel1.add(tp_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 162, 30));

        address_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_textActionPerformed(evt);
            }
        });
        jPanel1.add(address_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 79, 24));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, 30));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 790, 200));

        department_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department ID", "Department Name"
            }
        ));
        jScrollPane2.setViewportView(department_table);
        if (department_table.getColumnModel().getColumnCount() > 0) {
            department_table.getColumnModel().getColumn(0).setMinWidth(0);
            department_table.getColumnModel().getColumn(0).setPreferredWidth(0);
            department_table.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 240, 200));

        id_text.setEditable(false);
        id_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id_text.setEnabled(false);
        id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textActionPerformed(evt);
            }
        });
        getContentPane().add(id_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 297, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
        try {
            
            
            int row = department_table.getSelectedRow();
            
          
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Please select Department from department table", "information box" 
                        + "Warning", JOptionPane.INFORMATION_MESSAGE);
            } 
            
            
             else if (isValidStudentDetails("0")) {

              int departmentID = Integer.valueOf(department_table.getModel().getValueAt(row, 0).toString());
              String departmentName = department_table.getModel().getValueAt(row, 1).toString();
              int accYear = academicYear_Text.getText().equals("") ? 0 : Integer.valueOf(academicYear_Text.getText());
              int age=age_text.getText().equals("") ? 0 : Integer.valueOf(age_text.getText());
              String sql = "insert into student(first_name,last_name,nic_num,age,address,tp_num,reg_num,"
                       + "academic_year,department_id)values('" + fName_text.getText() + "','" + lName_text.getText() + 
                       "','" + nic_text.getText() + "',"+age+",'" + address_text.getText() +"',"+tp_text.getText() +",'" + reg_text.getText() + "',"+academicYear_Text.getText()+","+ departmentID + ")";
               DB_Connection con = new DB_Connection();
               int id = con.register(sql);
                // display values in table.
               DefaultTableModel model = (DefaultTableModel) student_table.getModel();
               model.addRow(new Object[]{id, fName_text.getText(), lName_text.getText(),
              nic_text.getText(), reg_text.getText(), age_text.getText(), address_text.getText(), tp_text.getText(), academicYear_Text.getText(),departmentID, departmentName});
              department_table.clearSelection();
              clearTestFields(); 
            }
                   
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_registrationActionPerformed

    private void fName_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fName_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fName_textActionPerformed

    private void reg_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_textActionPerformed

    private void tp_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tp_textActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
          clearTable();
          clearTestFields(); 
         // student_table.clearSelection();
          String sql="select * from student inner join department on student.department_id=department.department_id where ";
          DB_Connection con = new DB_Connection();
          String searchValue = jComboBox1.getSelectedItem().toString();
          
          if (searchValue.equals("Student Id")) {
          sql = sql + "student.student_id = '"+search_text.getText()+"'";
          }
          
          if (searchValue.equals("First Name")) {
          sql = sql + "student.first_name = '"+search_text.getText()+"'";
          }
          
          if (searchValue.equals("Last name")){
              sql=sql+"student.last_name = '"+search_text.getText()+"'";
          }
          
          if (searchValue.equals("NIC Num")){
            sql=sql+"student.nic_num ='"+search_text.getText()+"'";
    }
          if (searchValue.equals("Reg Num")){
            sql=sql+"student.reg_num ='"+search_text.getText()+"'";
          }
          if (searchValue.equals("Academic Year")){
          sql=sql+"student.academic_year="+search_text.getText()+"";
                  }
          ResultSet g=con.search(sql);
          search_text.setText("");
        try{
            DefaultTableModel tableModel = (DefaultTableModel)student_table.getModel();
             while(g.next()){
              Object[] arr = new Object[]{g.getString("student.student_id"),g.getString("student.first_name"),
                    g.getString("student.last_name"),g.getString("student.nic_num"),g.getString("student.reg_num"),g.getString("age"),g.getString("student.address"),g.getString("student.tp_num"),g.getString("student.academic_year"),g.getString("student.department_id"),g.getString("department.department_name")};
               tableModel.addRow(arr);           

            }
            
        }
        catch(Exception ex){
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {          
            int row = student_table.getSelectedRow();
            if(row==-1){
            JOptionPane.showMessageDialog( null,"Please select one from student details table", "information box" + "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
            String studentId = student_table.getModel().getValueAt(row, 0).toString();
            String firstName =  student_table.getModel().getValueAt(row, 1).toString();
            String lastName =  student_table.getModel().getValueAt(row, 2).toString();
            String nicNumber = student_table.getModel().getValueAt(row,3).toString();
            String regNo =  student_table.getModel().getValueAt(row,4).toString();
            String age =  student_table.getModel().getValueAt(row, 5).toString();
            String address=student_table.getModel().getValueAt(row,6).toString();
            String telephoneNum=student_table.getModel().getValueAt(row,7).toString();
            String academicYear=student_table.getModel().getValueAt(row,8).toString();
            String deartmentID=student_table.getModel().getValueAt(row,9).toString();
            String departmentName=student_table.getModel().getValueAt(row,10).toString();
        
            id_text.setText(studentId);
            fName_text.setText(firstName);
            lName_text.setText(lastName);
            nic_text.setText(nicNumber);
            reg_text.setText(regNo);
            age_text.setText(age);
            address_text.setText(address);
            tp_text.setText(telephoneNum);
            academicYear_Text.setText(academicYear);
   
            
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try { 
           int row = student_table.getSelectedRow();
           int depRow = department_table.getSelectedRow();
            if (depRow == -1) {
                JOptionPane.showMessageDialog(null, "Please select Department", "information box" 
                        + "Warning", JOptionPane.INFORMATION_MESSAGE);
            } else if (row == -1) {
                JOptionPane.showMessageDialog(null, "Please select Student ", "information box" 
                        + "Warning", JOptionPane.INFORMATION_MESSAGE);
            } else if (isValidStudentDetails(id_text.getText())) {
            int departmentid = Integer.valueOf(department_table.getModel().getValueAt(depRow, 0).toString());
            String departmentName= department_table.getModel().getValueAt(depRow,1).toString();
            String sql = "update student set first_name='"+fName_text.getText()+"',"
                    + "last_name='"+lName_text.getText()+"',nic_num='"+nic_text.getText()+"',reg_num='"+reg_text.getText()+"',age="+age_text.getText()+",address='"+address_text.getText()+"',tp_num='"+tp_text.getText()+"',academic_year="+academicYear_Text.getText()+",department_id="+departmentid+" where student_id="+id_text.getText()+"";
            System.out.println(sql);
            DB_Connection con=new DB_Connection();
               int id= con.register(sql);
                student_table.setValueAt(id, row, 0);
                student_table.setValueAt(fName_text.getText(), row, 1);
                student_table.setValueAt(lName_text.getText(), row, 2);
                student_table.setValueAt(nic_text.getText(), row, 3);
                student_table.setValueAt(reg_text.getText(), row, 4);
                student_table.setValueAt(age_text.getText(), row, 5);
                student_table.setValueAt(address_text.getText(), row, 6);
                student_table.setValueAt(tp_text.getText(), row, 7);
                student_table.setValueAt(academicYear_Text.getText(), row, 8);
                student_table.setValueAt(departmentid, row, 9);
                student_table.setValueAt(departmentName, row, 10);
              
                
               department_table.clearSelection();
               clearTestFields();
           }
           
           
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void search_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_textActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new MainApplication().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_textActionPerformed

    private void nic_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic_textKeyTyped
       char enter = evt.getKeyChar();

       if(nic_text.getText().length()<8){
            if(!(Character.isDigit(enter))){
            evt.consume();
        }
       }
          
        if (nic_text.getText().length()==9) {
           if((Character.isDigit(enter))){
            evt.consume();
        }
      }
        
        
         if (nic_text.getText().length()>9) {
           
            evt.consume();
        
      }
        
        
        
    }//GEN-LAST:event_nic_textKeyTyped

    private void tp_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tp_textKeyTyped

        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
        evt.consume();
        }
      if (tp_text.getText().length()>9) {
         evt.consume();
      }
          
    }//GEN-LAST:event_tp_textKeyTyped

    private void fName_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fName_textKeyTyped
        char enter = evt.getKeyChar();
        if((Character.isDigit(enter))){
            evt.consume();
        }
       
    }//GEN-LAST:event_fName_textKeyTyped

    private void lName_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lName_textKeyTyped
          char enter = evt.getKeyChar();
        if((Character.isDigit(enter))){
            evt.consume();
        }
       
    }//GEN-LAST:event_lName_textKeyTyped

    private void academicYear_TextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_academicYear_TextKeyTyped
         char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_academicYear_TextKeyTyped

    private void age_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_textKeyTyped
      char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_age_textKeyTyped

    private void lName_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lName_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lName_textActionPerformed

    private void nic_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nic_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nic_textActionPerformed

    private void age_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_textActionPerformed

    private void address_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_textActionPerformed

    private void academicYear_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academicYear_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_academicYear_TextActionPerformed

    private void fName_textPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fName_textPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fName_textPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField academicYear_Text;
    private javax.swing.JTextField address_text;
    private javax.swing.JTextField age_text;
    private javax.swing.JTable department_table;
    private javax.swing.JTextField fName_text;
    private javax.swing.JTextField id_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField lName_text;
    private javax.swing.JTextField nic_text;
    private javax.swing.JTextField reg_text;
    private javax.swing.JToggleButton registration;
    private javax.swing.JTextField search_text;
    private javax.swing.JTable student_table;
    private javax.swing.JTextField tp_text;
    // End of variables declaration//GEN-END:variables
}
